[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "mkdir -p uploads",
  "chmod 755 uploads",
  "cd ../config-app && npm install && npm run build",
  "cp -r ../config-app/dist config-app-dist"
]

[start]
cmd = "node src/server.js"
